[package]
name = "booth_archiver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# https://github.com/rustwasm/wasm-pack/issues/1247
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
getrandom = { version = "0.2", features = ["js"] }
worker = "0.0.18"
clap = { version = "4.3.19", features = ["derive"] }
indicatif = { version = "0.17.5", features = ["improved_unicode", "rayon"] }
lazy_static = "1.4.0"
path-absolutize = "3.1.0"
rayon = "1.7.0"
ron = "0.8.0"
rust_xlsxwriter = "0.45.0"
scraper = "0.17.1"
serde = { version = "1.0.177", features = ["derive"] }
serde_json = "1.0.104"
ureq = { version = "2.7.1", features = ["cookies", "cookie_store", "json", "serde", "serde_json"] }

[profile.release]
lto = true
strip = true
codegen-units = 1

