[package]
name = "booth_archiver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
indicatif = { version = "0.17.5", features = ["improved_unicode"] }
lazy_static = "1.4.0"
path-absolutize = "3.1.0"
reqwest = { version = "0.11.18", features = ["cookies", "json", "blocking"] }
scraper = "0.17.1"
serde = { version = "1.0.177", features = ["derive"] }
serde_json = "1.0.104"
structopt = "0.3.26"
