[target.x86_64-pc-windows-msvc]
# LLD linker
#
# You may need to install it:
#
# ```
# cargo install -f cargo-binutils
# rustup component add llvm-tools
# ```
linker = "rust-lld.exe"
rustflags = [
    # Nightly
    #    "-Zshare-generics=y",
    "-Zthreads=0",
    #    "--cfg", "tokio_unstable",
    #    "--cfg", "tracing_unstable",
]